yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<str:slug>/', views.group_posts, name='group_posts'),
    path('profile/<username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit')
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about'))
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        related_name="posts",
        blank=True,
        null=True
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )

    class Meta:
        ordering = ["-pub_date"]

    def __str__(self):
        return self.text

yatube/users/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    body = models.TextField()
    is_answered = models.BooleanField(default=False)

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        help_texts = {
            'text': 'Введите текст публикации',
            'group': 'Укажите группу публикации',
        }

yatube/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .models import Contact

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'subject', 'body')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from yatube.settings import ITEMS_PER_PAGE

from .forms import PostForm
from .models import Group, Post, User


def pagination(request, queryset):
    paginator = Paginator(queryset, ITEMS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return {
        'paginator': paginator,
        'page_namber': page_number,
        'page_obj': page_obj,
    }


def index(request):
    posts = Post.objects.all()
    context = pagination(request, posts)
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    context = {
        'group': group,
        'posts': posts,
    }
    context.update(pagination(request, posts))
    return render(request, 'posts/group_list.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()
        return redirect('posts:profile', post.author)
    return render(request, 'posts/post_create.html', {'form': form})


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    title = username
    context = {
        'author': author,
        'title': title,
    }
    context.update(pagination(request, posts))
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    count = post.author.posts.count()
    context = {
        'post': post,
        'count': count,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if request.user == post.author:
        form = PostForm(request.POST or None, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/post_create.html', context)

yatube/users/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm, ContactForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'


def user_contact(request):
    form = ContactForm()
    template = 'users/contact.html'
    context = {
        'form': form,
    }
    return render(request, template, context)

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}
  Об авторе проекта 
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-10 p-3">
      <h4>
        Привет! Я автор проекта, Кочетков Александр
      </h4>
      <p>Мне 30 лет, живу в Ростове-на-Дону и работаю экономистом.
        Мои умения верстать просто швах
      </p>
    </div>
  </div>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %} 
  Технологии
{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-10 p-3">
    <h4>Использованные технологии:</h4>
    <aside class="col-12 col-md-9">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Python
        </li>
        <li class="list-group-item">
          Django
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <hr>
        Проект разработан на старом ноутбуке с помощью Visual Studio Code
        и подсказок товарищей с Яндекс.Практикума
      <hr>
    </article>
  </div>
</div>
{% endblock %}

yatube/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static "img/logo.png" %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "img/fav/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "img/fav/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "img/fav/favicon-16x16.png" %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}     
    </header>
    <main>
    {% block content %} {% endblock %} 
    </main>       
    <footer class="border-top text-center py-3">
     {% include 'includes/footer.html' %}   
    </footer>
  </body>

yatube/templates/core/403csrf.html
{% extends "base.html" %}
{% block content %}
  <h1>Custom CSRF check error. 403</h1>
{% endblock %}

yatube/templates/includes/footer.html
{% load static %}
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static "img/logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube</a>
      </a>
      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %} <!-- проверка, активен ли блок для подсветки -->
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Об авторе</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
          </li>
          {% if user.username %}
            <li class="nav-item">
            <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'users:password_change_form' %}active{% endif %}"
                href="{% url 'users:password_change_form' %}">Изменить пароль</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}"
                href="{% url 'users:logout' %}">Выйти</a>
            </li>
            <li>
              Пользователь: {{ user.username }}
            <li>
          {% else %}
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
                href="{% url 'users:login' %}">Войти</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
                href="{% url 'users:signup' %}">Регистрация</a>
            </li>
          {% endif %}
        {% endwith %}
      </ul>
    </div>
  </nav>
</header>

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}
  {{ group.title }}
{% endblock %}
{% block content %}
  <div class="container">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
        <ul>
          <li>Автор: {{ post.author.get_full_name }} {{ post.author.username }}
            <a href="{% url "posts:profile" post.author %}">
              все посты пользователя
            </a>
          </li>
          <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
        </ul>
        <p>{{ post.text }}</p>
        <a href="{% url "posts:post_detail" post.id %}">подробная информация</a>
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  <div>
{% endblock %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends "base.html" %}
  {% block content %}
    <div class="container py-5">     
    {% block title %} {% endblock %}
        <h1>Последние обновления на сайте</h1>
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }} {{ post.author.username }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>      
          <p>
            {{ post.text|linebreaksbr }}
          </p>
          {% if post.group %}
            <a href="{% url "posts:group_posts" post.group.slug %}" >все записи группы</a>
          {% endif %}
            {% if not forloop.last %}<hr>
          {% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}  
    </div>  
  {% endblock %} 

yatube/templates/posts/post_create.html
{% extends "base.html" %} 
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}
{% endblock %}
{% block content %}
  <main>
    <div class="container py-1">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              {% if is_edit %}
                Редактировать пост
              {% else %}
                Новый пост
              {% endif %}
            </div>
            <div class="card-body">
              <form method="post">
                {% csrf_token %}
                <div class="form-group row my-3 p-3">
                  <label for="id_text">
                    Текст поста                  
                    <span class="required text-danger" >*</span>
                  </label>
                   <textarea name="text" cols="40" rows="10" class="form-control" required id={{ form.text }}</textarea>
                  <small id="id_text-help" class="form-text text-muted">
                    {% if is_edit %}
                      Текст редактируемого поста
                    {% else %}
                      Текст нового поста
                    {% endif %}
                  </small>
                </div>
                <div class="form-group row my-3 p-3">
                  <label for="id_group">Group</label>
                  <select name="group" class="form-control" id="id_group"><option value={{ form.group }}</option></select>
                  <small id="id_group-help" class="form-text text-muted">Группа, к которой будет относиться пост</small>
                </div>
                <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %} 
                </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    Пост {{ post|truncatechars:30 }}
{% endblock %}

{% block content %}
    <main>
      <div class="container py-4">
        <div class="row">
          <aside class="col-12 col-md-4">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
              {% if post.group %}
                <li class="list-group-item">
                  Группа: {{ post.group }}
                  <a href="{% url 'posts:group_posts' post.group.slug %}">
                    все записи группы
                  </a>
                </li>
              {% endif %}
                <li class="list-group-item">
                  Автор: {{ post.author.get_full_name }} {{ post.author.username }}
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                Всего постов автора: <span >{{ count }}</span>
              </li>
              <li class="list-group-item">
                <a href="{% url 'posts:profile' post.author %}">
                  все посты пользователя
                </a>
              </li>
            </ul>
          </aside>
          <article class="col-12 col-md-8">
            <p>
              {{ post.text|linebreaksbr }}
            </p>
            {% if request.user == post.author %}
              <a href="{% url 'posts:post_edit' post.id %}">
                Редактировать пост
              </a>
            {% endif %}
          </article>
        </div>
      </div>
    </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %} Профайл пользователя {{ post.author.get_full_name }} {{ post.author.username }}{% endblock %}
{% block content %}
    <div class="container py-5">
        <h1>Все посты пользователя {{ post.author.get_full_name }} {{ post.author.username }} </h1>
        <h3>Всего постов: {{ author.posts.all.count }} </h3>
        {% for post in page_obj %}
            <article>
                <ul>
                    <li>
                        Автор: {{ post.author.get_full_name }} {{ post.author.username }}
                        <a
                                href="{% url 'posts:profile' post.author.username %}">все
                            посты пользователя</a>
                    </li>
                    <li>
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                </ul>
                <p>{{ post.text }}</p>
                <a href="{% url 'posts:post_detail' post.id %}">подробная
                    информация </a>
            </article>
            {% if post.group.slug %}
                <a href="{% url 'posts:group_posts' post.group.slug %}">все
                    записи группы</a>
            {% else %}
            {% endif %}
            {% if not forloop.last %}
                <hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}

{% block title %}
  Вы вышли из системы
{% endblock title %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Выход
        </div>
        <div class="card-body">
          <p>
            Вы вышли из своей учётной записи. Ждём вас снова!
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}
  Войти
{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}
          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}>
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}>
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %}Пароль изменён{% endblock %}
{% block content%}
  {% load user_filters %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">Пароль изменён</div>
              <div class="card-body"><p>Пароль изменён успешно</p></div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}
  Пароль сброшен
{% endblock %}

{% block content%}
  {% load user_filters %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль восстановлен
              </div>
              <div class="card-body">
                <p>Пароль сохранен. Используйте его для входа</p>
                <a href="{% url 'users:login' %}">войти</a>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
    </main>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}
  Новый пароль
{% endblock %}

{% block content%}
  {% load user_filters %}
  {% if validlink %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Введите новый пароль
              </div> <!-- card-hader -->
              <div class="card-body">
                <form method="post" action="{% url 'users:password_reset_complete' %}">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
                    <small id="id_new_password1-help" class="form-text text-muted">
                      <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                    </small>      
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">      
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Назначить новый пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div> <!-- container -->
    </main>
  {% else %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Ошибка</div>
            <div class="card-body">
              <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
            </div> <!-- card-body -->
          </div> <!-- card-header -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  {% endif %}
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block title %}
  Сброс пароля
{% endblock %}

{% block content%}
{% load user_filters %}
  <main>
    <div class="container py-5"> 
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
            </div>
            <div class="card-body">
              <form method="post" action="{% url 'users:password_reset_form' %}">
                {% csrf_token %}
                <div class="form-group row my-3 p-3">
                  <label for="id_email">
                    Адрес электронной почты
                    <span class="required text-danger">*</span>
                  </label>    
                  <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
                </div>
                <div class="col-md-6 offset-md-4">
                  <button type="submit" class="btn btn-primary">
                    Сбросить пароль
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </main>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}
  Зарегистрироваться
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
        <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}